baseURL = 'http://m0on.xyz/'
languageCode = 'en-us'
title = 'm0on@localhost blog'
theme = 'risotto'
author = 'Max Stanford-Taylor'
copyright = '© 2021 Max Stanford-Taylor'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Max 'm0on' Stanford-Taylor"
description = "18 y/o developer, FPV pilot and occational musician"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/manfromth3m0oN"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:m0on@tuta.io"

[menu]

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[markup.goldmark.renderer]
unsafe = true

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
